import { mkdir, writeFile } from 'node:fs/promises';
import { homedir } from 'node:os';
import { join } from 'node:path';
import { newId, type Artifact } from '@ainp/shared';
import { store } from './store/store';
import { createArtifact, audit } from './workflow-engine';

const REPORTS_DIR = process.env.AINP_REPORTS_DIR ?? join(homedir(), '.ai-native', 'reports');

/**
 * Completion Report — server-side assembly. Pulls every persisted record for
 * the run and renders a markdown summary. The same data is exposed as JSON in
 * `metadata.json` so the UI can render without re-querying.
 *
 * IMPORTANT: this is the audit/source-of-truth handoff, not a sales doc.
 * Every claim must cite an evidence row.
 */
export async function generateCompletionReport(workflowRunId: string): Promise<Artifact> {
  const run = store.workflowRuns.get(workflowRunId);
  if (!run) throw new Error(`workflow run not found: ${workflowRunId}`);

  const project = store.projects.get(run.projectId);
  const steps = store.stepRuns.byWorkflow(workflowRunId);
  const commands = store.commandRuns.byWorkflow(workflowRunId);
  const gates = store.gateRuns.byWorkflow(workflowRunId);
  const artifacts = store.artifacts.byWorkflow(workflowRunId);
  const builds = store.buildRuns.byWorkflow(workflowRunId);
  const approvals = store.approvals.byWorkflow(workflowRunId);

  const stageRow = (stage: string): string => {
    const ss = steps.filter((s) => s.stage === stage);
    if (ss.length === 0) return `| ${stage} | — | — |`;
    const last = ss[ss.length - 1]!;
    return `| ${stage} | ${last.status} | ${last.completedAt ?? last.startedAt ?? ''} |`;
  };

  const gateRow = (g: (typeof gates)[number]): string =>
    `| ${g.gateId} | ${g.status} | ${g.ruleResults.map((r) => `${r.ruleId}=${r.status}`).join('; ')} |`;

  const md = [
    `# Completion Report`,
    ``,
    `- **Workflow Run:** \`${run.id}\``,
    `- **Title:** ${run.title}`,
    `- **Project:** ${project?.name ?? run.projectId}`,
    `- **Branch:** \`${run.branch}\``,
    `- **Workspace:** \`${run.workspacePath ?? '-'}\``,
    `- **Status:** ${run.status}`,
    ``,
    `## Stage timeline`,
    ``,
    `| Stage | Status | At |`,
    `|---|---|---|`,
    [
      'requirement',
      'design',
      'implementation',
      'build_test',
      'review',
      'completion',
      'knowledge',
    ]
      .map(stageRow)
      .join('\n'),
    ``,
    `## Gates`,
    ``,
    `| Gate | Status | Rules |`,
    `|---|---|---|`,
    gates.length === 0 ? `| (none) | | |` : gates.map(gateRow).join('\n'),
    ``,
    `## Build & Tests`,
    ``,
    builds.length === 0
      ? '_No Maven builds recorded._'
      : builds
          .map((b) => {
            const ts = store.testRuns.byBuild(b.id);
            const counts = ts
              .map(
                (t) =>
                  `${t.framework}: total=${t.total} passed=${t.passed} failed=${t.failed} errors=${t.errors} skipped=${t.skipped}`,
              )
              .join('\n');
            return `- BuildRun \`${b.id}\` status=${b.status} jdk=${b.jdkVersion} cmd=\`${b.mavenCommand}\`\n${counts ? counts.split('\n').map((l) => `  - ${l}`).join('\n') : ''}`;
          })
          .join('\n'),
    ``,
    `## Commands (${commands.length})`,
    ``,
    commands.length === 0
      ? '_no commands_'
      : commands
          .map(
            (c) =>
              `- \`${c.command}\` -> ${c.status} exit=${c.exitCode} (${c.durationMs}ms) stdout=${c.stdoutRef}`,
          )
          .join('\n'),
    ``,
    `## Artifacts (${artifacts.length})`,
    ``,
    artifacts.length === 0
      ? '_no artifacts_'
      : artifacts.map((a) => `- ${a.kind}: \`${a.uri}\``).join('\n'),
    ``,
    `## Approvals (${approvals.length})`,
    ``,
    approvals.length === 0
      ? '_no approvals_'
      : approvals
          .map((a) => `- ${a.gateId}: ${a.decision} by ${a.actor}${a.comment ? ` — ${a.comment}` : ''}`)
          .join('\n'),
    ``,
    `_Generated by ainp-api at ${new Date().toISOString()}._`,
  ].join('\n');

  const outDir = join(REPORTS_DIR, workflowRunId);
  await mkdir(outDir, { recursive: true });
  const reportId = newId('art');
  const path = join(outDir, `${reportId}.md`);
  await writeFile(path, md, 'utf8');
  audit(workflowRunId, 'completion_report.generated', { path });

  return createArtifact({
    workflowRunId,
    stepRunId: null,
    kind: 'completion_report',
    uri: `file://${path}`,
    size: Buffer.byteLength(md, 'utf8'),
    contentType: 'text/markdown',
    metadata: { generatedAt: new Date().toISOString() },
  });
}

/**
 * Knowledge Candidate — distilled from the completed run. Marked as a
 * candidate; only the human Knowledge Gate promotes it into long-term
 * memory.
 */
export async function generateKnowledgeCandidate(workflowRunId: string): Promise<Artifact> {
  const run = store.workflowRuns.get(workflowRunId);
  if (!run) throw new Error(`workflow run not found: ${workflowRunId}`);

  const builds = store.buildRuns.byWorkflow(workflowRunId);
  const buildSummary =
    builds.length === 0
      ? 'No Maven build was executed.'
      : builds
          .map((b) => `- BuildRun ${b.id}: status=${b.status}, cmd=\`${b.mavenCommand}\``)
          .join('\n');

  const testRuns = builds.flatMap((b) => store.testRuns.byBuild(b.id));
  const testSummary =
    testRuns.length === 0
      ? 'No test reports collected.'
      : testRuns
          .map(
            (t) =>
              `- ${t.framework}: total=${t.total} passed=${t.passed} failed=${t.failed} errors=${t.errors}`,
          )
          .join('\n');

  const diffArtifact = store.artifacts.byKind(workflowRunId, 'diff').at(-1) ?? null;

  const md = [
    `# Knowledge Candidate`,
    ``,
    `- **From workflow run:** \`${run.id}\``,
    `- **Title:** ${run.title}`,
    ``,
    `## Status`,
    `Candidate. Will be promoted into long-term knowledge only after the`,
    `Knowledge Gate is approved by a human.`,
    ``,
    `## What was changed`,
    diffArtifact ? `Diff artifact: \`${diffArtifact.uri}\`` : '_No diff artifact found._',
    ``,
    `## Build outcome`,
    buildSummary,
    ``,
    `## Test outcome`,
    testSummary,
    ``,
    `## Reusable lessons`,
    `- The Trusted Local Worktree mode is sufficient for low-risk Java edits.`,
    `- Compile/Test gates blocked on real \`mvn\` exit code, not on agent self-reports.`,
    `- Diff scope can be enforced cheaply with prefix matches; sensitive paths still need a human.`,
    ``,
    `## Provenance`,
    `Generated from artifacts, command runs, and gate runs persisted on this`,
    `workflow run. See the matching Completion Report for evidence refs.`,
    ``,
    `_Generated at ${new Date().toISOString()}._`,
  ].join('\n');

  const outDir = join(REPORTS_DIR, workflowRunId);
  await mkdir(outDir, { recursive: true });
  const id = newId('art');
  const path = join(outDir, `${id}.md`);
  await writeFile(path, md, 'utf8');
  audit(workflowRunId, 'knowledge_candidate.generated', { path });

  return createArtifact({
    workflowRunId,
    stepRunId: null,
    kind: 'knowledge_candidate',
    uri: `file://${path}`,
    size: Buffer.byteLength(md, 'utf8'),
    contentType: 'text/markdown',
    metadata: { generatedAt: new Date().toISOString() },
  });
}
